#!/bin/bash
git init -qqq
git remote add origin https://github.com/AyoubJadouli/docker-magento
git fetch origin -qqq
git checkout origin/master
mv iac/.vscode ./
rm -rf  .git
mkdir src
chmod 777 src
git init
